apiVersion: v1
kind: Service
metadata:
  name: linkding-service
  namespace: flux-system
spec:
  selector:
    app: linkding
  ports:
    - protocol: TCP
      port: 80       # The port you want to use outside
      targetPort: 9090 # The port Linkding is listening on inside
  type: ClusterIP
